# Site settings
title: Portfolio
description: Has stuff about me
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Joseph Livni
user_description: I'm a Software Engineer, graduating from the University of Oregon in December 2018. Growing up with Legos, I've always had a passion for building. Computer science has allowed me to continue this passion combined wiith the feeling of pride that comes with introducing  new tech into the world. I like ultimate frisbee, Oregon in the Fall, and IPAs.
user_title: Software Developer
email: j.d.livni@gmail.com
github_username:  Lebonesco
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
