# Site settings
title: Joseph Livni
description: a site about Joseph Livni
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Joseph Livni
user_description: I'm a Software Engineer, graduating from the University of Oregon in December 2018. I've always had a passion for building and problem solving. Computer science has allowed me to continue this passion, combined with the feeling of accomplishment that comes with introducing new tech into the world. Since, I began my journey into the world of computer science, I've worked on numerous professional teams, working on code that has included frontend, backend, and internal tools to name a few. Besides keeping up on the latest tech and financial news, I like ultimate frisbee, Oregon in the Fall, and IPAs.
user_title: Software Developer
email: j.d.livni@gmail.com
github_username:  Lebonesco
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-30759437-1"

exclude: ['package.json', 'src' , 'node_modules']

articles: [
    {
      "content":"The cache is one of the greatest innovations of computer\nscience.\nIt significantly reduces work on the CPU",
      "date": "Mon, 07 Jan 2019 16:16:01 GMT",
      "link": "https://hackernoon.com/build-a-go-cache-in-10-minutes-c908a8255568?source=rss-d24b5a950413------2",
      "title": "Build a Go Cache in 10 Minutes"
    },
    {   
      "content": "Compilers are awesome! They combine theory and application and touch on a lot of software
      related topics ",
      "date": "Mon, 07 Jan 2019 14:54:04 GMT",
      "link": "https://medium.freecodecamp.org/write-a-compiler-in-go-quick-guide-30d2f33ac6e0?source=rss-d24b5a950413------2",
      "title": "How to write a compiler in Go: a quick guide"
		},
		{
			"content": "The inspiration for this post came from a project at work. I was building\na service that required the comparison of two ",
			"date": "Fri, 28 Dec 2018 12:16:00 GMT",
			"link": "https://hackernoon.com/create-a-go-json-parser-batteries-included-9d02d09fe508?source=rss-d24b5a950413------2",
			"title": "Create a Go Json Parser: Batteries Included"
		},
		# {
    #   "content": 'At my job I was building a service in Go that needed
    # to process a lot of user requests quickly. By encapsulating it with',
    #   "date": "Thu, 18 Oct 2018 19:35:19 GMT",
    #   "link": "https://medium.com/@j.d.livni/understanding-go-pipelines-in-5-minutes-2906a5c41496?source=rss-d24b5a950413------2",
    #   "title": "Understanding Go Pipelines in 5 minutes"
		# },
		{
			"content": "At my job I was building a service in Go that needed to process a lot of\nuser requests quickly. By encapsulating it with",
			"date": "Mon, 08 Oct 2018 00:02:05 GMT",
			"link": "https://medium.com/@j.d.livni/write-a-go-worker-pool-in-15-minutes-c9b42f640923?source=rss-d24b5a950413------2",
			"title": "Write a Go Worker Pool in 15 minutes"
		},
		# {
		# 	"content": "Instead of prepping for interviews I decided to procrastinate and write\nabout a cool piece of code, inspired by a simila",
		# 	"date": "Fri, 31 Aug 2018 23:07:21 GMT",
		# 	"link": "https://medium.com/@j.d.livni/create-a-load-bar-in-go-f158837ff4c4?source=rss-d24b5a950413------2",
		# 	"title": "Create a load bar in Go"
		# },
		# {
		# 	"content": "People have strong opinions about Go, both positive and negative. However,
    # 	like any tool it's about choosing the right o",
		# 	"date": "Sun, 26 Aug 2018 05:31:32 GMT",
		# 	"link": "https://medium.com/@j.d.livni/create-a-go-api-in-5-minutes-part-1-7d371089d742?source=rss-d24b5a950413------2",
		# 	"title": "Create a Go API in 5 minutes Part 1"
		# }
]
